on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: "17.0.10"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.22.2"
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{secrets.GITHUB_TOKEN}}
          commit: master
          tag: v1.0.${{github.run_number}}
